### ISSUE TITLE
Missing `mimic.py` file

### ISSUE THREAD

**Issue by Run542968** [jiawei-ren/insactor#3]
Hi Jiawei,

Thank you for your excellent work！

I followed the instructions to run the code, but when training the low-level controller following the command below, it seems that the `mimic.py` file is missing. 
> python mimic.py --config configs/controller/human_0.01.yaml

Can you include these files, or is there something I am missing from the instructions?
Thanks!

**Comment by jiawei-ren** [comment]
Thanks for pointing this out! I have just uploaded `mimic.py`.

**Comment by Run542968** [comment]
Thanks for your timely response! 

However, when I run the `mimic.py`, some errors occurred. It seems that some datalist files are missing. The specific location is in lines 43-49 of the `diffmimic/utils/data.py` file, referred to below.
https://github.com/jiawei-ren/insactor/blob/72db2fb7907acd943f3a0e1d05a724f1b638177f/diffmimic/utils/data.py#L43C1-L49C45

Can you include them or how can I generate these files？

Looking forward to your reply.

**Comment by jiawei-ren** [comment]
I have just uploaded them. Thank you again for that!

**Comment by Run542968** [comment]
Thank you for your timely handling! 

Sorry to bother you again. Related to the previous question, is the folder 'kit_texts' in line 45 of  `diffmimic/utils/data.py` (i.e., `text_dir = 'data/kit_texts'`) equivalent to the folder 'data/datasets/kit_pml/texts'? 

Because I find that the recent submission does not include 'data/kit_texts', also missing 'data/humanml3d_text'.

**Comment by jiawei-ren** [comment]
Yes, they are equivalent. I did not fix the text directory paths because texts are not actually used in the low-level tracker training. The text directories are there because we implemented a PADL baseline that requires text, and that baseline was not included during the code release. 

Sorry that the code is a bit messy now. Please don't hesitate to let me know if you run into any other problems.
